# Generated by Django 5.1.15 on 2026-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
